CELDEV-969 - [Security] May 2021 Upgrade Dependencies
celements/celements-test pull request #2
Opened 2021-06-07 04:34 UTC by fpichler

https://synjira.atlassian.net/browse/CELDEV-969

2021-06-07 10:54 UTC, ebeutler submitted a review, later dismissed

2021-06-07 11:02 UTC, fpichler commented
@msladek wdyt?

2021-06-09 15:43 UTC, msladek requested changes

2021-06-09 15:43 UTC, msladek commented on celements-common-test/pom.xml
> +	<parent>
```suggestion
  <parent>
```
replace all tabs in file

2021-06-09 18:07 UTC, fpichler commented on celements-common-test/pom.xml
> +	<parent>
done.

2021-06-10 01:03 UTC, msladek requested changes

2021-06-10 01:03 UTC, msladek commented on celements-common-test/pom.xml
> +		<!-- Add here all your dependencies -->
```suggestion
    <!-- Add here all your dependencies -->
```
some more tabs ...

2021-06-10 01:03 UTC, msladek commented on celements-common-test/pom.xml
> +    <tag>celements-shared-tests-1.6</tag>
```suggestion
```

2021-06-11 08:05 UTC, msladek submitted a review, later dismissed

2021-06-11 12:08 UTC, msladek approved these changes

2021-06-11 12:08 UTC, merged